### ISSUE TITLE
Is it possible to get this add-on for IceCat?

### ISSUE THREAD

**Issue by icewater** [gnome-integration-team/firefox-gnome#367]
I'm transitioning away from Firefox, and looking for another capable, well-integrated GNOME browser.  

Is it possible to get this add-on for IceCat?

GNOME Web is coming along well but it's not quite there yet for exclusive use.

**Comment by d9h02f** [comment]
IceCat is the same as Firefox but with some small modifications. You can use this extension/theme with it without any problems. Currently you shouldn't use it at all because it is based on a very old Firefox version with very grave unfixed vulnerabilities. This also means you'd need to use an older version of this extension for it to work with IceCat.

Once the newest version of IceCat is released, which should be based on Firefox 38, version 38 of this extension will work with it.

**Comment by seleznev** [comment]
@d9h02f, thank you for the answer!
